### ISSUE TITLE
Investigate using `/proc/self/fd` to implement `canonicalize` on Linux

### ISSUE THREAD

**Issue by sunfishcode** [sunfishcode/cap-std#80]
On Linux, `/proc/self/fd/*` are symlink-like objects on which one can do `readlink` to obtain canonical paths to open file descriptors. Musl for example [does this](https://git.musl-libc.org/cgit/musl/tree/src/internal/procfdname.c) to implement `realpath`, which is what Rust's libstd uses to implement `fs::canonicalize` on Unix-family platforms. `cap-std`'s `canonicalize` doesn't provide an absolute path, so it would need to strip leading components up to the point where the `Dir`'s directory starts.

Caution is indicated; Linux's `/proc` has a history of being tricky to work with. These symlink-like objects are "magic links" and have special behavior. And `/proc` may be mounted in a context where users may have the ability to manipulate it.

**Comment by kubkon** [comment]
FWIW, I don't think there is any other way of achieving this on Linux. On macOS though we can use `fcntl` with `F_GETPATH`, and on Windows it's `GetFinalPathNameByHandleW` which is a wrapper around several NTOS syscalls and is defined in `kernelbase` system library. As far as I know though, this type of a host query is not universally supported and for instance [FreeBSD doesn't expose any mechanism to achieve this](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=197695).
